// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeuQWBd-2UYLElav-7iI51GPdWJCYSOIw',
    appId: '1:128482972015:web:bd1426c4c08908b450189a',
    messagingSenderId: '128482972015',
    projectId: 'notes-4392f',
    authDomain: 'notes-4392f.firebaseapp.com',
    storageBucket: 'notes-4392f.appspot.com',
    measurementId: 'G-D8BRZVRHQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv0gycVJgFZrJ-vypvvmKks50TMo0OVhQ',
    appId: '1:128482972015:android:c479a7b1b05926a050189a',
    messagingSenderId: '128482972015',
    projectId: 'notes-4392f',
    storageBucket: 'notes-4392f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_2n-Nn5HhOr3e02jjPi6pCFlYA_AF0pY',
    appId: '1:128482972015:ios:b457f28eda9b84aa50189a',
    messagingSenderId: '128482972015',
    projectId: 'notes-4392f',
    storageBucket: 'notes-4392f.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_2n-Nn5HhOr3e02jjPi6pCFlYA_AF0pY',
    appId: '1:128482972015:ios:b457f28eda9b84aa50189a',
    messagingSenderId: '128482972015',
    projectId: 'notes-4392f',
    storageBucket: 'notes-4392f.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeuQWBd-2UYLElav-7iI51GPdWJCYSOIw',
    appId: '1:128482972015:web:3b6bcfc05e532db150189a',
    messagingSenderId: '128482972015',
    projectId: 'notes-4392f',
    authDomain: 'notes-4392f.firebaseapp.com',
    storageBucket: 'notes-4392f.appspot.com',
    measurementId: 'G-DG9BQNQK9S',
  );

}