// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8CnDUqc7k9U2gR0yvWII4ctEprgAj8Dc',
    appId: '1:548956990535:web:947684c7e80c831cb89562',
    messagingSenderId: '548956990535',
    projectId: 'flutterfirenelson',
    authDomain: 'flutterfirenelson.firebaseapp.com',
    storageBucket: 'flutterfirenelson.appspot.com',
    measurementId: 'G-NXPDGPVNDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6tuxHQPF6vmhWWwI1UqVPRaP_QWGwywQ',
    appId: '1:548956990535:android:2d1a8b2e68d70769b89562',
    messagingSenderId: '548956990535',
    projectId: 'flutterfirenelson',
    storageBucket: 'flutterfirenelson.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqU696BBZeNGa94I1A_cKlNL5rqWTpRUM',
    appId: '1:548956990535:ios:1ec329c3c5469b7ab89562',
    messagingSenderId: '548956990535',
    projectId: 'flutterfirenelson',
    storageBucket: 'flutterfirenelson.appspot.com',
    iosBundleId: 'com.example.flutterfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqU696BBZeNGa94I1A_cKlNL5rqWTpRUM',
    appId: '1:548956990535:ios:1ec329c3c5469b7ab89562',
    messagingSenderId: '548956990535',
    projectId: 'flutterfirenelson',
    storageBucket: 'flutterfirenelson.appspot.com',
    iosBundleId: 'com.example.flutterfire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8CnDUqc7k9U2gR0yvWII4ctEprgAj8Dc',
    appId: '1:548956990535:web:c7df6149357e34d9b89562',
    messagingSenderId: '548956990535',
    projectId: 'flutterfirenelson',
    authDomain: 'flutterfirenelson.firebaseapp.com',
    storageBucket: 'flutterfirenelson.appspot.com',
    measurementId: 'G-YX43YTQVC4',
  );
}
